### ISSUE TITLE
Unable to convert SVG to PNG on OS X

### ISSUE THREAD

**Issue by bulyshko** [cssho/vscode-svgviewer#17]
```
spawn /Users/USERNAME/.vscode/extensions/cssho.vscode-svgviewer-1.1.11/node_modules/phantomjs/lib/phantom\phantomjs.exe ENOENT
```

**Comment by cssho** [comment]
Workaround : `npm rebuild` on `/Users/USERNAME/.vscode/extensions/cssho.vscode-svgviewer-1.1.11/`

**Comment by bulyshko** [comment]
@cssho Why would one need a workaround? This should work after installation.

**Comment by cssho** [comment]
@bulyshko Exactly. I will examine the handling of that.

**Comment by g3o2** [comment]
This feature does still not appear to work. A message appears after `Export PNG` specifying the path of the supposed  `.png` file but there's nothing. I've installed the latest release (1.1.12) in vscode 1.4.0 on Mac OS X 10.11.6.

**Comment by kexi** [comment]
as well as Ubuntu16.04LTS (Node.js not installed).

@Georgeouz 

launch terminal then type

```
which npm
```

if no result,

# Solution 1

 install [Node.js](https://nodejs.org/) first, and then restart vscode.
because of using `npm` command to export png.

# Solution 2

download vsix
https://github.com/kexi/vscode-svgviewer/releases/tag/20160902
launch terminal to install vsix, then type

``` bash
code vscode-svgviewer-1.1.12.vsix
```

use "(Experimental) Export PNG" menu to export PNG.

I'm working on #19 .
